# 添加并配置第三方数据库连接池Druid
spring:
  datasource:
    # MySQL数据库连接配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&userSSL=false
    username: root
    password: 123456
    # 添加并配置第三方数据库连接池Druid
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 10
    maxActive: 20

# 配置Mybatis
mybatis:
  # 配置Mybatis的XML映射文件路径
  mapper-locations: classpath:mapper/*.xml
  # 配置XML映射文件中指定的实体类别名路径
  type-aliases-package: com.hyy.po
  configuration:
    # 开启驼峰命名匹配映射
    map-underscore-to-camel-case: true
    # 控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 配置日志
logging:
  lever:
    root: info
    com.hyy: debug
  file:
    name: log/blog-dev.log
server:
  port: 8080

